import CONFIG from './config';

const POPULAR = CONFIG.POPULAR_MOVIE_URL + CONFIG.API_KEY;
const { BASE_URL } = CONFIG;
const SEARCH_URL = CONFIG.SEARCH_URL + CONFIG.API_KEY;

export { POPULAR, BASE_URL, SEARCH_URL };
